.gitignore, gulpfile.js, server.js, server/marketing/marketingController.js, tests/server.js
make sure you have a .env.test file, the edits to the gulp file require this
=> get server ready for deployment, and add Welcome email confirmation

client/css/homepage.css, server/user/userController.js
=> mobile menu bar, & code cleanup

gulpfile.js, package.json, server.js, server/email/emailController.js, server/email/emailModel.js, server/marketing/marketingModel.js, server/payment/paymentController.js, server/user/userController.js, server/user/userModel.js, tests/server.js
Cleanup lots of ESLint and JSLint errors, and fix the `Can Calculate Total Earnings` test
=> code cleanup

server/email/emailController.js, server/user/userController.js, tests/server.js
=> fix craaaaaaaazy server bug

client/css/homepage.css, client/index.html, server/email/emailController.js
=> mobile responsive homepage

server/user/userController.js
To move the logout redirection to the client for @csreyes
=> (fix) send back confirmation on successful logout, instead of redirection

server/email/emailController.js, server/marketing/marketingController.js, server/payment/paymentController.js, server/user/userController.js, tests/server.js
Fixes the logout test now that we are keeping their username cookie, and cleans up some stray code that ESLint was warning about.
=> Fix logout test and code cleanup

server/user/userModel.js
Stripe will handle that. Avoids duplicate error from null value
=> (fix) stripeId doesn't need to be unique

server.js, server/user/userController.js, tests/server.js
here's a description. I'm testing out the `hub pull-request` CLI feature.
=> (feat) add forgot username to server

client/index.html
This adds an ASCII message to the console on the index.html landing page:
```
,     ,            /)              /)        
___  __     _   // __   _  _   _(/         
/_(_)_(_/ (_  (_(_(/_/ (__(/_(_(_(_(_ (_/_ o  
.-/                                     .-/      
(_/                                     (_/       
```
Thank you and have a good day.
=> (feat) add console message to index.html

package.json, server.js, server/user/userController.js
Lays out the beginning of the Forgot Password server logic
=> (feat) add Forgot Password to server

server/user/userController.js
this pull request subtracts $0.25 from the user balance before withdrawing, to cover the Stripe transfer charge.
The other changes are just to fix indentation for linting errors.
=> (fix) $0.25 deduction on transfers to users to cover Stripe fees

client/css/payment.css, client/expired-reset-password-token.html, client/invalid-reset-password-token.html, client/js/components/forgotpassword.js, client/js/components/resetpassword.js
* switches link color on the static Invalid Reset Token pages to match our color scheme
* adds <title>s to the Invalid Reset Token pages
* makes Send Reset Email a single line, for proper sizing
* hides new password text on Reset Password page
=> misc ui improvements to Reset Password pages

server/email/emailController.js, server/marketing/marketingController.js, server/payment/paymentController.js, server/user/userController.js, views/jenkins.jade, views/welcomeEmail.jade
This fixes all the email and cname domains so that each test environment gets it own test environment.
* We won't need to share one ngrok address any more.
* It will be clearer which server is sending auto-messages just by looking at the message.
* All of the links in the auto-emails will work properly without needing to be modified, and point to the correct server.
You need to change your local environment variables to `DOMAIN={YOURFIRSTNAME}.gilded.club`.
And then use ngrok with `ngrok -subdomain={YOURFIRSTNAME}-gilded 8080`
=> Fix domains for test and dev environments

server/user/userController.js
=> (fix) add missing comma to newUserEmail

server/marketing/marketingController.js
=> (fix) add `domains` var, never declared in marketingController

client/js/components/vip.js, client/less/dashboard/vip.less
=> Fix empty VIP graphic quirk and add VIP description

server/email/emailController.js
Hardcodes our emails into the system...
=> (feat) forward admin@, jenkins@, welcome@, and payments@ to the admins

client/js/stores/store.js
since we're showing a real welcome email now
=> (fix) Remove fake email from store

server.js, server/email/emailController.js
**UNSURE** if this is ready to be merged in yet. Hasn't been tested.
=> (feat) add basic email.compose function and server route

server/email/emailController.js
* fixes status code from `201 Created` to `200 OK`
* doesn't send full file contents of all user's received attachments on every Dashboard load
=> fixes for GET Dashboard

client/js/components/account.js, client/js/components/payments.js, client/js/components/vip.js, client/less/dashboard/settings.less
=> (style) Revert forward email input + add margin between inputs and buttons

server.js, server/email/emailController.js
was still passing all the tests two days ago. haven't touched this code since then.
=> cleanup some of the email controller code
